### PR TITLE
Type and uuid positions need to be swapped

### PR DESCRIPTION
**Pull request by yjkhtddx**
generateWsDiscoveryProbePayload function call error.

### CODE REVIEW

**Comment by patrickmichalina** [comment]
@yjkhtddx hey did you get an error when using it? Somehow I have not seen this issue and it makes me curious how it happened to you? Do you have an error screen?

**Comment by yjkhtddx** [comment]
@patrickmichalina 
I can't discover all my cameras.
I use wirshak to find the content of the onvif package is wrong.
Cameras that strictly use the onvif protocol did not respond.

**Comment by patrickmichalina** [comment]
@yjkhtddx are they working now?

**Comment by yjkhtddx** [comment]
@patrickmichalina
Thank you for releasing version 7.0.3. It's working right now.

**Pull request merged**
